# nlp/training_data.py

TRAINING_DATA = {

    "academics": [
        "Show academic calendar",
        "When are semester exams?",
        "Syllabus for R22",
        "Curriculum details",
        "Regulation document",
        "Semester schedule",
        "Academic regulations",
        "R18 syllabus",
        "R22 regulation",
        "Download syllabus",
        "Course curriculum",
        "Exam dates",
        "Academic timetable",
        "Semester calendar",
        "Regulations pdf",
        "Course structure",
        "Academic year details",
        "University syllabus",
        "Academic information",
        "Semester exam dates"
    ],

    "admissions": [
        "Admission process",
        "Eligibility criteria",
        "How to apply?",
        "Courses offered",
        "Admission procedure details",
        "Entrance exam for admission",
        "Admission fee details",
        "Btech admission",
        "How to join college",
        "Admission requirements",
        "Apply for admission",
        "Admission eligibility",
        "Seat allotment",
        "Admission form",
        "Application process",
        "Admission notification",
        "Admission guidelines",
        "Admission dates",
        "Admission enquiry",
        "Undergraduate admission"
        "How to make e payment?",
        "How to pay admission fee?",
        "Online fee payment details",
        "How to pay college fees?",
        "How to pay fees online?",
        "What courses are offered?",
        "List of courses available",
        "B.Tech courses offered",
        "Admission eligibility details",
        "Eligibility criteria for admission",
        "Explain eligibility conditions",

    ],

    "departments": [
        "Who is HOD?",
        "Faculty list",
        "Department vision",
        "Department achievements",
        "Teaching staff details",
        "Department mission",
        "Department faculty",
        "CSE department",
        "ECE department",
        "Mechanical department",
        "Civil department",
        "Department information",
        "Department staff",
        "Department profile",
        "Department courses",
        "Department facilities",
        "Department overview",
        "Department activities",
        "Department research",
        "Head of department"
        "Freshman engineering vision",
        "Vision of freshman engineering",
        "Freshman engineering mission",
        "Show freshman engineering department",
        "Freshman engineering details",
        "Tell me about freshman engineering"

    ],

    "examinations": [
        "Exam timetable",
        "Exam notifications",
        "Results declared?",
        "Hall ticket download",
        "Exam schedule",
        "Semester exam timetable",
        "Exam result date",
        "Exam time table",
        "Examination notice",
        "Exam circular",
        "Internal exam dates",
        "External exam dates",
        "Exam updates",
        "Exam form",
        "Exam details",
        "Mid exam schedule",
        "Final exam schedule",
        "Exam announcement",
        "Exam results",
        "Download hall ticket"
    ],

    "placements": [
        "Placement statistics",
        "Recruiters list",
        "Top companies visited",
        "Placement percentage",
        "Year wise placements",
        "Campus placements",
        "Placement record",
        "Highest package",
        "Average package",
        "Placement companies",
        "Placement details",
        "Placement drive",
        "Company visits",
        "Placement report",
        "Placement cell",
        "Training and placement",
        "Placement data",
        "Placement updates",
        "Placement information",
        "Placement opportunities"
        "placements",
        "placement details",
        "training and placement",
        "who are the recruiters",
        "recruiters",
        "recruiting companies",
        "companies visiting campus",
        "placement companies",
        "year wise placements",
        "placement officer"
        "training and placement coordinators"
        "placement contact details"
        "placement contacts"
        "student coordinators for placements"
    ],

    "general_info": [
        "Hostel details",
        "Hostel facilities",
        "Hostel fee",
        "Library timings",
        "Library information",
        "Computer center info",
        "Infrastructure details",
        "College facilities",
        "NCC training",
        "NCC events",
        "Research centre details",
        "Board of studies",
        "Centre of excellence",
        "Transport facility",
        "Bus facility",
        "Health center",
        "Campus facilities",
        "College infrastructure",
        "Lab facilities",
        "Sports facilities"
    ],

    "contact": [
        "College phone number",
        "Email address",
        "College location",
        "Office contact details",
        "Contact information",
        "Contact number",
        "College email",
        "Phone number",
        "Address of college",
        "How to contact college",
        "Principal contact",
        "Administration contact",
        "College address",
        "Contact office",
        "College mobile number",
        "Contact details",
        "Reach the college",
        "Office phone number",
        "College contact details",
        "Contact email"
    ],

    "research": [
        "R and D",
        "R&D",
        "research activities",
        "research cell",
        "innovation cell",
        "Newgen IEDC",
        "newgen innovation",
        "centre for excellence",
        "center of excellence",
        "AICTE idea lab",
        "idea lab",
        "innovation programs",
        "college research",
        "research and development"
        "Tell me about R&D",
        "Research and development details",
        "R&D cell information",
        "Explain AICTE Idea Lab",
        "Newgen IEDC details",
        "Centre for Excellence information",
        "Innovation cell details",
        "IEDC program",
        "Research cell",
        "AICTE lab details"
    ],
    "student_clubs": [
    "Tell me about clubs",
    "What clubs are there in college?",
    "List student clubs",
    "About clubs in college",
    "Explain student clubs",
    "Clubs information",
    "Tell me about coders club",
    "Explain NSS club",
    "Eco club details",
    "Newgen club information",
    "Women’s chapter club",
    "Sports club details",
    "Radio club information"
    ],


}
